/**
 * Turning one prompt into image bytes: the part every vendor shares.
 *
 * The vendor-specific half — which path, which body, which completion literal,
 * where the picture hides — lives one directory down in `image/`, one file per
 * vendor; `image/provider.ts` says why it is shaped that way. What is left here
 * is everything that must behave identically no matter who drew the picture:
 *
 * - **The bytes.** A provider answers with either base64 it already decoded or a
 *   URL, and this module is what turns a URL into bytes. That keeps the
 *   attachment store's own size ceiling in one place, which matters because it
 *   is defeatable otherwise: MJ's four-up grid arrives at 8.5 MB.
 * - **The media type.** Sniffed from the bytes, never taken from a declaration.
 *   The attachment store fully decodes them and refuses a type that disagrees
 *   (`attachment-local/src/store.ts`: `IMAGE_TYPE_MISMATCH`), and the format
 *   genuinely varies within one family — the same prompt got PNG from
 *   `gemini-2.5-flash-image` and JPEG from `gemini-3-pro-image`.
 * - **Partial success is success.** A reply carrying four pictures of which
 *   three are usable returns those three and reports the fourth. Only an empty
 *   result is an error.
 *
 * @module openlux-plugin-account/media/images
 */

import type { Context } from '@deepseek-ai/cordis'
import type { ImageMediaType } from '@deepseek-ai/dsh-attachment'
import { AccountRequestError, normalizeBase, requestBytes } from '../account/http.ts'
import type { ConsoleAccess } from '../market/console.ts'
import type { ImageCarrier, ImageProvider, ImageRequest } from './image/provider.ts'
import { ImageGenerationError } from './image/provider.ts'

export { ImageGenerationError } from './image/provider.ts'

/** Budget for pulling one produced picture; the bytes are already generated. */
const TRANSFER_TIMEOUT_MS = 60_000

/** One generated image, ready for the attachment store. */
export interface GeneratedImageBytes {
  readonly data: Uint8Array
  /** Sniffed from the bytes, never from what the response claimed. */
  readonly mediaType: ImageMediaType
  /** The prompt the upstream says it actually used, when it rewrote ours. */
  readonly revisedPrompt?: string
}

/** What one call produced, in the vocabulary the tool reports. */
export interface GeneratedImages {
  readonly images: readonly GeneratedImageBytes[]
  /** One line per picture that arrived but could not be used. */
  readonly failures: readonly string[]
  /** One line per requested value this transport has no field for. */
  readonly ignored: readonly string[]
}

/** File signatures of the four formats the attachment store accepts. */
const SIGNATURES: readonly { readonly type: ImageMediaType; readonly test: (data: Uint8Array) => boolean }[] = [
  { type: 'image/png', test: data => starts(data, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]) },
  { type: 'image/jpeg', test: data => starts(data, [0xff, 0xd8, 0xff]) },
  { type: 'image/gif', test: data => starts(data, [0x47, 0x49, 0x46, 0x38]) },
  // RIFF container with a WEBP form type; the four bytes between are the size.
  { type: 'image/webp', test: data => starts(data, [0x52, 0x49, 0x46, 0x46]) && starts(data.subarray(8), [0x57, 0x45, 0x42, 0x50]) },
]

/** Whether these bytes begin with this signature. */
function starts(data: Uint8Array, signature: readonly number[]): boolean {
  if (data.byteLength < signature.length) return false
  return signature.every((byte, index) => data[index] === byte)
}

/**
 * Identify the format of generated bytes.
 * @param data - the complete encoded image.
 * @returns the media type, or undefined when it is not one of the four.
 */
export function sniffImageType(data: Uint8Array): ImageMediaType | undefined {
  return SIGNATURES.find(entry => entry.test(data))?.type
}

/**
 * Generate images with one vendor and return their bytes.
 * @param ctx - host context.
 * @param access - route origin and token reader.
 * @param provider - the vendor adapter chosen for this model.
 * @param request - what to generate.
 * @param maxBytes - per-image ceiling, from the attachment service's own limit.
 * @param signal - caller cancellation, forwarded to every request.
 * @returns the usable images, the reasons for any that were not, and what the
 * transport had no field for.
 * @throws {ImageGenerationError} when the route refused, or nothing usable arrived.
 */
export async function generateImages(
  ctx: Context,
  access: ConsoleAccess,
  provider: ImageProvider,
  request: ImageRequest,
  maxBytes: number,
  signal?: AbortSignal,
): Promise<GeneratedImages> {
  const token = await access.apiKey()
  if (token === undefined || token === '') {
    throw new ImageGenerationError('当前没有可用的 OpenLux 密钥，请先在侧栏登录账号。')
  }
  const root = normalizeBase(access.baseUrl)
  const outcome = await provider.generate({
    ctx,
    root,
    base: `${root}/v1`,
    headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
    maxBytes,
    ...signal === undefined ? {} : { signal },
  }, request)

  const images: GeneratedImageBytes[] = []
  const failures: string[] = []
  for (const [index, carrier] of outcome.carriers.entries()) {
    const label = `第 ${String(index + 1)} 张`
    try {
      const data = await bytesOf(ctx, carrier, maxBytes, signal)
      const mediaType = sniffImageType(data)
      if (mediaType === undefined) {
        failures.push(`${label}：返回的不是 PNG / JPEG / WebP / GIF（前 4 字节 ${hex(data)}），无法作为附件保存。`)
        continue
      }
      images.push({
        data,
        mediaType,
        ...carrier.revisedPrompt === undefined ? {} : { revisedPrompt: carrier.revisedPrompt },
      })
    } catch (error: unknown) {
      if (error instanceof AccountRequestError && error.kind === 'cancelled') throw error
      failures.push(`${label}：${error instanceof Error ? error.message : String(error)}`)
    }
  }
  if (images.length === 0) {
    throw new ImageGenerationError(`出图接口返回了 ${String(outcome.carriers.length)} 条结果，但没有一条可用。`
      + `\n${failures.join('\n')}`)
  }
  return { images, failures, ignored: outcome.ignored }
}

/**
 * Read one produced picture's bytes, from whichever carrier it used.
 * @param ctx - host context.
 * @param carrier - what the provider answered with.
 * @param maxBytes - per-image ceiling.
 * @param signal - caller cancellation.
 * @returns the encoded image bytes.
 * @throws {Error} when the download failed or the picture is too large.
 */
async function bytesOf(
  ctx: Context,
  carrier: ImageCarrier,
  maxBytes: number,
  signal?: AbortSignal,
): Promise<Uint8Array> {
  if (carrier.kind === 'bytes') {
    if (carrier.data.byteLength > maxBytes) {
      throw new Error(`返回的图片超过本机附件上限（${size(carrier.data.byteLength)} > ${size(maxBytes)}），`
        + '请用更小的 size 重试。')
    }
    return carrier.data
  }
  try {
    return await requestBytes(ctx, carrier.url, TRANSFER_TIMEOUT_MS, maxBytes, signal, '图片')
  } catch (error: unknown) {
    if (error instanceof AccountRequestError && error.kind === 'cancelled') throw error
    if (error instanceof AccountRequestError) throw new Error(error.message)
    throw error
  }
}

/** The first four bytes, for a message about bytes nobody can identify. */
function hex(data: Uint8Array): string {
  return [...data.subarray(0, 4)].map(byte => byte.toString(16).padStart(2, '0')).join(' ')
}

/** Bytes as a short human-readable size. */
export function size(bytes: number): string {
  if (bytes < 1024) return `${String(bytes)} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
